FROM amazonlinux:2018.03

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
RUN yum install diffutils gcc72 gcc72-c++ openssl-devel pkg-config capnproto -y
RUN curl -O https://capnproto.org/capnproto-c++-0.8.0.tar.gz && tar zxf capnproto-c++-0.8.0.tar.gz && \
    cd capnproto-c++-0.8.0 && ./configure && make -j6 check && make install
RUN source "$HOME/.cargo/env" && cargo install assemblylift-cli

WORKDIR /usr/src
COPY . .
RUN source "$HOME/.cargo/env" && cargo build -p file:///usr/src/modules/http --release

RUN mkdir ./bin && cp ./modules/http/target/release/akkoro-std-http ./bin/akkoro-std-http
RUN export IOMOD_VERSION=$(cat ./iomod.toml | grep version -m 1 | awk '{print $3}' | sed 's/"//g')
RUN zip -r akkoro.std.http@$(IOMOD_VERSION).iomod ./bin/akkoro-std-http ./iomod.toml

CMD cat ./iomod.toml | grep version -m 1 | awk '{print $3}' | sed 's/"//g'
